---
title: "Wybory na szczeblu lokalnym"
author: "Michał Pierzgalski i Paweł Stępień"
subtitle: '2017'
output:
  revealjs::revealjs_presentation:
    reveal_options:
      chalkboard:
        theme: blackboard
        toggleNotesButton: no
    reveal_plugins: chalkboard
    self_contained: no
    theme: solarized
  pdf_document: default
  html_document: default
---

# Metody wyłaniania rządzących w wyborach (Systemy głoswania)

## System głosowania/wyborczy - definicja

**System głosowania** jest systemem reguł, na których podstawie
przeprowadzany jest podział zbioru niepodzielnych i jednorodnych dóbr/rzeczy/uprawnień (np. mandatów).

## System głosowania/wyborczy

... jest określony przez konfigurację następujących parametrów:

1. typ/rodzaj formuły (metody) wyborczej (typ tzw. funkcji społecznego wyboru)
2. kształt i rozmiar okręgów wyborczych
3. projekt (typ) kart do głosowania i uprawnienia wyborców w trakcie głosowania
4. [OPCJONALNIE] formalny próg reprezentacji

## Formuła wyborcza

#### Voting method/allocation method

Funkcja $f$, która odwzorowuje tzw. *zredukowany profil preferencji* głosujących na zbiór dóbr/uprawnień (np. mandatów) przeznaczonych do podziału.

$$f : \{v_1, v_2, ..., v_n\} \rightarrow \{s_1, s_2, ..., s_n\}$$
$n$ = liczba kandydatów/partii

## Indywidulany profil preferencji

#### Wyborcy: X, Y i Z

| Pozycja | X | Y | Z |
| - | - | - | - |
| 1 | Kandydat a2 | Kandydat a1 | Kandydat a1 |
| 2 | Kandydat a1 | Kandydat a2 | Kandydat a2 |
| 3 | Kandydat a3 | Kandydat a3 | Kandydat a3 |

## Zredukowany profil preferencji

**JEŚLI** : zakładamy, że liczą sie tylko pierwsze preferencje

|    Kandydaci   | a1 | a2 | a3 |
| -     | - | - | - |
| $v_i$ | 2 | 1 | 0 |



## Uproszczona typologia systemów wyborczych

- systemy większościowe (plurality/majority systems)
- systemy reprezentacji proporcjonalnej
- systemy mieszane

## 
